[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
xnomad_launch = "56SUkQRjKkAJzB1esPwn25tgvsW3TuwgzncvUh5rGT1C"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
